const $=id=>document.getElementById(id),canvas=$('scene'),ctx=canvas.getContext('2d');
let objects,events,step=0,selected='root',timer=null,yaw=.65,pitch=.38,zoom=1,drag=null,projection='orthographic';
const titles={bound:'Bound the entire scene',split:'Partition into eight octants',assign:'Assign object references',leaf:'Check the stopping criteria',done:'An octree, constructed'};
function statusLabel(status){return status==='internal'?'internal node':status==='leaf'?'leaf node':status;}
function pause(){clearInterval(timer);timer=null;$('play').textContent='Play';}
function restart(){pause();objects=Octree.scene($('preset').value);events=Octree.build(objects,+$('depth').value,+$('capacity').value);step=0;selected='root';$('timeline').max=events.length-1;for(const id of ['depth','capacity'])$(id+'-value').textContent=$(id).value;update();}
function go(n){step=Math.max(0,Math.min(events.length-1,n));selected=events[step].id;if(step===events.length-1)pause();update();}
function update(){const e=events[step],nodes=e.nodes,node=nodes[selected];$('timeline').value=step;$('step-count').textContent=`Step ${step+1} of ${events.length}`;$('back').disabled=!step;$('next').disabled=step===events.length-1;$('play').disabled=step===events.length-1;$('phase-title').textContent=titles[e.phase];$('phase-text').textContent=e.text;const phase={bound:0,split:1,assign:2,leaf:3,done:3}[e.phase];$('phase-number').textContent='0'+(phase+1);document.querySelectorAll('.phases span').forEach((el,i)=>el.classList.toggle('active',i===phase));$('node-title').textContent=node.label.split('/').join(' → ');const refs=Octree.descendantRefs(nodes,selected);$('node-info').textContent=`Depth ${node.depth} · ${statusLabel(node.status)}${node.reason&&node.reason!=='within capacity'?' · '+node.reason:''}`;$('members').innerHTML=node.children.length?`8 child nodes · 0 stored object references<br>${Octree.countLabel(refs.length,'unique object')} in descendants`:`${Octree.countLabel(node.refs.length,'stored object reference')}<br>`+node.refs.map(i=>`<span style="color:${objects[i].color}">● ${objects[i].name}</span>`).join(' &nbsp; ');let list=[];function walk(id){const n=nodes[id];list.push(n);n.children.forEach(walk);}walk('root');$('tree').replaceChildren(...list.map(n=>{const b=document.createElement('button');b.className='tree-row'+(n.status==='pending'?' pending':'')+(selected===n.id?' selected':'');b.style.setProperty('--node-indent',n.depth*10+'px');b.innerHTML=`<span>${n.children.length?'▾':'·'} ${n.label.split('/').pop()}</span><span class="status">${statusLabel(n.status)}</span><span class="count">${n.children.length?'':Octree.countLabel(n.refs.length,'object reference')}</span>`;b.onclick=()=>{selected=n.id;update();};return b;}));draw();}
function project(p){const root=events[0].nodes.root,center=root.min.map((v,i)=>(v+root.max[i])/2);let [x,y,z]=p.map((v,i)=>v-center[i]);let a=x*Math.cos(yaw)-z*Math.sin(yaw),b=x*Math.sin(yaw)+z*Math.cos(yaw),c=y*Math.cos(pitch)-b*Math.sin(pitch),d=y*Math.sin(pitch)+b*Math.cos(pitch);// Positive d is toward the camera. Keep it outside the scene and ground grid.
const cameraDistance=4;
const perspectiveScale=projection==='perspective'?cameraDistance/(cameraDistance-d):1;
const scale=Math.min(canvas.clientWidth,canvas.clientHeight)*.32*zoom*perspectiveScale;return [canvas.clientWidth/2+a*scale,canvas.clientHeight/2-c*scale+10,d];}
const edges=[[0,1],[0,2],[0,4],[1,3],[1,5],[2,3],[2,6],[3,7],[4,5],[4,6],[5,7],[6,7]];
function corners(b){return Array.from({length:8},(_,k)=>[0,1,2].map(i=>(k&(4>>i))?b.max[i]:b.min[i]));}
function line(points,color,width=1,dash=[]){ctx.beginPath();points.map(project).forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.stroke();ctx.setLineDash([]);}
function wire(b,color,width=1,dash=[]){const c=corners(b);edges.forEach(([a,b])=>line([c[a],c[b]],color,width,dash));}
function polygon(points,fill,stroke){const q=points.map(project);ctx.beginPath();q.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=.5;ctx.stroke();}}
function shade(hex,f,alpha){return '#'+[1,3,5].map(i=>Math.round(parseInt(hex.slice(i,i+2),16)*f).toString(16).padStart(2,'0')).join('')+alpha;}
function draw(){if(!events)return;const dpr=window.devicePixelRatio||1;canvas.width=canvas.clientWidth*dpr;canvas.height=canvas.clientHeight*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);const e=events[step],nodes=e.nodes,root=nodes.root,chosen=nodes[selected],refs=Octree.descendantRefs(nodes,selected);const y=root.min[1]-.12;for(let t=-1.2;t<=1.21;t+=.2){line([[-1.2,y,t],[1.2,y,t]],'#e5eaed');line([[t,y,-1.2],[t,y,1.2]],'#e5eaed');}
let faces=[];objects.forEach(p=>{const alpha=refs.includes(p.id)?'e8':'35';if(p.type==='box'){const c=corners(p);[[0,1,3,2],[4,6,7,5],[0,4,5,1],[2,3,7,6],[0,2,6,4],[1,5,7,3]].forEach((ids,j)=>faces.push({points:ids.map(i=>c[i]),color:shade(p.color,[.7,1,.78,.95,.82,.9][j],alpha),stroke:'#ffffff55'}));}else{const point=(u,v)=>[p.center[0]+p.radius*Math.sin(u)*Math.cos(v),p.center[1]+p.radius*Math.cos(u),p.center[2]+p.radius*Math.sin(u)*Math.sin(v)];for(let a=0;a<12;a++)for(let b=0;b<20;b++){let u=a*Math.PI/12,v=b*Math.PI/10;faces.push({points:[point(u,v),point(u+Math.PI/12,v),point(u+Math.PI/12,v+Math.PI/10),point(u,v+Math.PI/10)],color:shade(p.color,.68+.3*Math.max(0,Math.cos(u)*.8+Math.sin(u)*Math.cos(v)*.4-Math.sin(u)*Math.sin(v)*.3),alpha),stroke:null});}}});faces.sort((a,b)=>a.points.reduce((s,p)=>s+project(p)[2],0)/a.points.length-b.points.reduce((s,p)=>s+project(p)[2],0)/b.points.length).forEach(f=>polygon(f.points,f.color,f.stroke));
Object.values(nodes).filter(n=>!n.children.length&&n.refs.length).forEach(n=>wire(n,'#7c98a54d',.8));wire(root,'#6c85918c',1.2);
if(e.phase==='split'){const n=nodes[e.id],mid=n.min.map((v,i)=>(v+n.max[i])/2);for(let axis=0;axis<3;axis++){const others=[0,1,2].filter(i=>i!==axis);const pts=[[0,0],[1,0],[1,1],[0,1]].map(bits=>{const p=[...mid];others.forEach((j,k)=>p[j]=bits[k]?n.max[j]:n.min[j]);return p;});polygon(pts,['#de7a6d22','#5ea78322','#548ed422'][axis]);line([...pts,pts[0]],['#d66d5f','#339477','#5588cf'][axis],1.5);}}
if(e.phase==='assign'&&selected===e.id)chosen.children.forEach(id=>wire(nodes[id],'#279b8b80',1.2));wire(chosen,'#128d75',2.5);
objects.forEach(p=>{const q=project(p.center);ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillStyle=refs.includes(p.id)?'#243443':'#9aa6ae';ctx.fillText(p.name,q[0],q[1]+4);});const origin=[root.min[0],root.min[1],root.min[2]];['x','y','z'].forEach((name,i)=>{const end=[...origin];end[i]+=.3;line([origin,end],['#d17167','#359a7d','#568ccc'][i],2);const q=project(end);ctx.fillStyle=['#d17167','#359a7d','#568ccc'][i];ctx.fillText(name,q[0]+9,q[1]-6);});}
$('back').onclick=()=>{pause();go(step-1);};$('next').onclick=()=>{pause();go(step+1);};$('play').onclick=()=>{if(timer)pause();else{$('play').textContent='Pause';timer=setInterval(()=>go(step+1),1200);}};$('timeline').oninput=()=>{pause();go(+$('timeline').value);};$('reset').onclick=restart;['depth','capacity','preset'].forEach(id=>$(id).oninput=restart);$('projection').onchange=()=>{projection=$('projection').value;draw();};$('camera').onclick=()=>{yaw=.65;pitch=.38;zoom=1;draw();};canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;yaw-=(e.clientX-drag[0])*.008;pitch=Math.max(-1.4,Math.min(1.4,pitch+(e.clientY-drag[1])*.008));drag=[e.clientX,e.clientY];draw();};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.55,Math.min(2,zoom*Math.exp(-e.deltaY*.001)));draw();},{passive:false});new ResizeObserver(draw).observe(canvas);restart();
